# Browser: chrome | firefox | edge
browser=chrome

# Target application base URL
base.url=https://the-internet.herokuapp.com

# Explicit wait timeout in seconds
explicit.wait=10

# Run browser in headless mode: true | false
headless=false
